{% set version = "2.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggm/ggm_{{ version }}.tar.gz
  sha256: 6fbbbb81bbdb408f99196d19486b542778607acf169bd1ee1ba3e73a5205e0ae

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-biocmanager
    - r-graph
    - r-igraph
  run:
    - r-base
    - r-biocmanager
    - r-graph
    - r-igraph

test:
  commands:
    - $R -e "library('ggm')"           # [not win]
    - "\"%R%\" -e \"library('ggm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggm
  license: GPL-2.0-only
  summary: Functions and datasets for maximum likelihood fitting of some classes of graphical Markov models.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
