travis:
  secure:
    BINSTAR_TOKEN: nXRwz47LSkh7/kgeVNOV4X9unDCAPKDstzJb/tmONuoB9h1MmAoDqQMihceQA0G9I3s8MX4F4dszdMqbogWT/rtj5hyYSnbXgrSEV1pcw+OCiJzVr3fpxMjO+9iE//vGdTWTiFRHnoTLVmWu88aMz9jOXcG27cK0Ws/BtJqfzai0mshUKLBbtqXRjFLaKltBdgKbfYihVHXHmEUBFX/JEUxUVR0ighCF/FcfYQDvnDGwsyif8S9Lb9wW59yAzIhwKVSVGF+17dTvEcEMvKFzT1lL6/Sz7d4/Ai1BtWXwK7qCgtJDdghERrA/OqAPErYXGjzCkktCYf4N2WFMx5OPFow0Q88Rtfn/sY5f5PJvvbE+NqNTzilGqZayv6ZtcG8By4pNWZ2O01g9HMnhODPrImHTuylp8Zt/KLT3f5YteH0v9uTaF1cpk8V6m3omBgw9MPgOqR/io88+oMSBQoQCwx/rwVBdSTpnM798QivTwKTkjf+OUu8ZCjHlfJKX5t9nngl1CJW7ZYGW8gc2xBlzYa1UGiDmX5Oxzz3ZDJ+iFCwT9fcJ4zBq/tpz9CldIKofYsZuWXnYamsMfMz6Fl3TClb28kWDQnDdhGrOY8hzUnRjNhXPPbBl4sTn4xgwmuBJvWw0+ebQD8L1lf35IWGYtytIqvbcMFzHtffze+z04mQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
