travis:
  secure:
    BINSTAR_TOKEN: DrJhnEV25rPHWJ07Q4+f771Nvgi0ivCGOfBsDCgZkRU3otomtHLwow4V2KGw++SNBYM17xSwd+ldXBxmglZR8aE+AlKCnT25M2fLX1PFQnS3mLbF+7bFiRpqN7h/zMRXWis7lUOeiTQ3Ev5JAKktzRxmA1NohP/89TftgYwXrGyhAHluxAERu0J2iq9bwiHPIU29fpF+9eXRYTZJiZrwFwxGy19mUGB89ra4bB0vsMf394iONn+fqr3XvRlBzrLXPTYK0tQv1kUKt65VKPDYF4WrdZkMElAnP0pZy3VmVTNkTeznla4OmEDFsqzWl1xt5pht5xmgXVwzMSN1rhmn36GGHfdUkru+sHqR/itN8uZHibfkP/icWRV0ZoWDmk5r5QE53SnH+m3Rtu7PUdJ3OiwQDmEc0aDy7iTExc9PiRc3W4mI4S/yTu/1zHlF9ZZPjsixByTdhE0u/PM5jh7BOuO9wxi06rMW757TZleBm52XbZQhu6S7iiWLeE7xNuJjDFoAB/9cbamLUul9i1ECNuD8YKKbmeIL4W7Njaph6zp1nvEbBdMBW/fbzEeIZr0SYI+WpJoC1kFshVq8ZhUXsHqSqfkTRvLiE9Nt/xL7pxcGcyIqDHfJgBxTkMpmxPwOGiSslZ16pcgF4GqjSz+c64UNj0Hxk1zVpAAID8MPyQg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
